### ISSUE TITLE
Not working anymore, same with the firefox extension.

### ISSUE THREAD

**Issue by zchryy03** [sowdust/searchbook-chrome#1]
The red bar at the bottom shows it's intercepting but doesn't show any results.

**Comment by fabykika** [comment]
It's the same, I hope it can be solved 😥

**Comment by fabykika** [comment]
It's the same, I hope it can be solved

**Comment by ghost** [comment]
isnt this is the same as my issue?

**Comment by zchryy03** [comment]
I guess it's just the same. gonna close this one

**Comment by ghost** [comment]
oh i see,  its for chrome,  duh!  i am so tired i am totally stupid.  sorry.
